---
branches:
  only:
    - master

sudo: required

services:
  - docker

install:
  - sudo pip install ansible==2.2
  - >
    ansible-galaxy install
    --role-file=./tests/requirements.yml
    --roles-path=./tests/dependencies
    --force

before_script:
  - >
    docker build
    --no-cache
    --pull
    --tag ansible-roles-test
    tests/support

script:
  - >
    docker run
    --interactive
    --tty
    --volume $PWD:/etc/ansible/roles/letsencrypt
    --volume $PWD/tests/dependencies:/etc/ansible/roles/letsencrypt/tests/roles:ro
    --env AWS_ACCESS_KEY=$AWS_ACCESS_KEY
    --env AWS_SECRET_KEY=$AWS_SECRET_KEY
    --workdir /etc/ansible/roles/letsencrypt/tests
    ansible-roles-test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
