---
branches:
  only:
    - master

sudo: required

services:
  - docker

env:
  - distro: wheezy

install:
  - sudo pip install ansible==2.2
  - ansible-galaxy install --force -r ./tests/requirements.yml -p ./tests/dependencies

before_script:
  - docker build --no-cache -t ansible-roles-test-${distro} tests/support

script:
  - >
    docker run -it
    -v $PWD:/etc/ansible/roles/letsencrypt
    -v $PWD/tests/dependencies:/etc/ansible/roles/letsencrypt/tests/roles:ro
    --env AWS_ACCESS_KEY=$AWS_ACCESS_KEY
    --env AWS_SECRET_KEY=$AWS_SECRET_KEY
    --workdir /etc/ansible/roles/letsencrypt/tests
    ansible-roles-test-${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
